import "./globals.css";
import Nav from "../components/Nav";
import Sidebar from "../components/Sidebar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className=" w-full h-screen bg-gradient-to-r from-cyan-500 to-blue-500">
        <Nav />
        <div className="flex flex-col items-center w-full pt-5">{children}</div>
      </body>
    </html>
  );
}
